/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'latitude' at '16. 11. 11 오후 4:04' with Gradle 2.1
 *
 * @author latitude, @date 16. 11. 11 오후 4:04
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
